project_name: gcs-uploader
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: gcs-uploader
    env:
      - CGO_ENABLED=1
    goos:
      - windows
      - darwin
    goarch:
      - amd64
release:
  prerelease: auto
